### ISSUE TITLE
Unable to run e2e tests on macos

### ISSUE THREAD

**Issue by naveensrinivasan** [kubernetes-sigs/security-profiles-operator#194]
#### What happened:
Unable to e2e test on osx
#### What you expected to happen:
Able to run e2e tests on osx

#### How to reproduce it (as minimally and precisely as possible):

<details>
      <summary>make test-e2e</summary>
      

```
go test -timeout 40m -count=1 ./test/... -v
=== RUN   TestSuite
cluster-type: kind
I0114 10:40:49.347318   83140 suite_test.go:288]  "msg"="Setting up suite"
=== RUN   TestSuite/TestSecurityProfilesOperator
I0114 10:40:49.347847   83140 suite_test.go:288]  "msg"="Deploying the cluster"
    suite_test.go:133:
        	Error Trace:	suite_test.go:133
        	            				suite.go:148
        	Error:      	Expected nil, but got: &os.PathError{Op:"fork/exec", Path:"/Users/naveen/go/src/github.com/naveensrinivasan/security-profiles-operator/build/kind", Err:0x8}
        	Test:       	TestSuite/TestSecurityProfilesOperator
I0114 10:40:49.350537   83140 suite_test.go:288]  "msg"="Waiting for cluster to be ready"
time="2021-01-14T10:40:49-05:00" level=info msg="+ /usr/local/bin/kubectl wait --for condition=ready nodes --all"
Unable to connect to the server: dial tcp 192.168.99.106:8443: i/o timeout
    suite_test.go:246:
        	Error Trace:	suite_test.go:246
        	            				suite_test.go:274
        	            				suite_test.go:137
        	            				suite.go:148
        	Error:      	Expected nil, but got: command /usr/local/bin/kubectl wait --for condition=ready nodes --all did not succeed: Unable to connect to the server: dial tcp 192.168.99.106:8443: i/o timeout
        	Test:       	TestSuite/TestSecurityProfilesOperator
I0114 10:43:19.447856   83140 suite_test.go:288]  "msg"="Destroying cluster"
time="2021-01-14T10:43:19-05:00" level=info msg="+ /Users/naveen/go/src/github.com/naveensrinivasan/security-profiles-operator/build/kind delete cluster --name=spo-e2e-1610638849 -v=3"
    suite_test.go:246:
        	Error Trace:	suite_test.go:246
        	            				suite_test.go:151
        	            				suite.go:141
        	            				panic.go:969
        	            				panic.go:212
        	            				signal_unix.go:742
        	            				command.go:326
        	            				suite_test.go:247
        	            				suite_test.go:274
        	            				suite_test.go:137
        	            				suite.go:148
        	Error:      	Expected nil, but got: &os.PathError{Op:"fork/exec", Path:"/Users/naveen/go/src/github.com/naveensrinivasan/security-profiles-operator/build/kind", Err:0x8}
        	Test:       	TestSuite/TestSecurityProfilesOperator
    suite.go:63: test panicked: runtime error: invalid memory address or nil pointer dereference
        goroutine 16 [running]:
        runtime/debug.Stack(0xc00014b500, 0x1facf40, 0x2b34520)
        	/usr/local/Cellar/go/1.15.6/libexec/src/runtime/debug/stack.go:24 +0x9f
        github.com/stretchr/testify/suite.failOnPanic(0xc000102f00)
        	/Users/naveen/go/pkg/mod/github.com/stretchr/testify@v1.6.1/suite/suite.go:63 +0x57
        panic(0x1facf40, 0x2b34520)
        	/usr/local/Cellar/go/1.15.6/libexec/src/runtime/panic.go:969 +0x1b9
        k8s.io/release/pkg/command.(*Stream).OutputTrimNL(...)
        	/Users/naveen/go/pkg/mod/k8s.io/release@v0.4.1/pkg/command/command.go:326
        sigs.k8s.io/security-profiles-operator/test_test.(*e2e).run(0xc00012a100, 0xc0004d6a20, 0x56, 0xc00014b780, 0x4, 0x4, 0x19, 0x10e9651)
        	/Users/naveen/go/src/github.com/naveensrinivasan/security-profiles-operator/test/suite_test.go:247 +0xc1
        sigs.k8s.io/security-profiles-operator/test_test.(*kinde2e).TearDownTest(0xc00012a100)
        	/Users/naveen/go/src/github.com/naveensrinivasan/security-profiles-operator/test/suite_test.go:151 +0x14d
        github.com/stretchr/testify/suite.Run.func1.1(0xc000114030, 0xc000102f00, 0x1ef6e90, 0x1c, 0x0, 0x0, 0x22e0ee0, 0xc000481920, 0xc000481920, 0xc000114b28, ...)
        	/Users/naveen/go/pkg/mod/github.com/stretchr/testify@v1.6.1/suite/suite.go:141 +0x103
        panic(0x1facf40, 0x2b34520)
        	/usr/local/Cellar/go/1.15.6/libexec/src/runtime/panic.go:969 +0x1b9
        k8s.io/release/pkg/command.(*Stream).OutputTrimNL(...)
        	/Users/naveen/go/pkg/mod/k8s.io/release@v0.4.1/pkg/command/command.go:326
        sigs.k8s.io/security-profiles-operator/test_test.(*e2e).run(0xc00012a100, 0xc000128460, 0x16, 0xc00014bc48, 0x5, 0x5, 0x0, 0x2111260)
        	/Users/naveen/go/src/github.com/naveensrinivasan/security-profiles-operator/test/suite_test.go:247 +0xc1
        sigs.k8s.io/security-profiles-operator/test_test.(*e2e).kubectl(...)
        	/Users/naveen/go/src/github.com/naveensrinivasan/security-profiles-operator/test/suite_test.go:274
        sigs.k8s.io/security-profiles-operator/test_test.(*kinde2e).SetupTest(0xc00012a100)
        	/Users/naveen/go/src/github.com/naveensrinivasan/security-profiles-operator/test/suite_test.go:137 +0x41c
        github.com/stretchr/testify/suite.Run.func1(0xc000102f00)
        	/Users/naveen/go/pkg/mod/github.com/stretchr/testify@v1.6.1/suite/suite.go:148 +0x658
        testing.tRunner(0xc000102f00, 0xc0000de090)
        	/usr/local/Cellar/go/1.15.6/libexec/src/testing/testing.go:1123 +0xef
        created by testing.(*T).Run
        	/usr/local/Cellar/go/1.15.6/libexec/src/testing/testing.go:1168 +0x2b3
--- FAIL: TestSuite (150.10s)
    --- FAIL: TestSuite/TestSecurityProfilesOperator (150.10s)
FAIL
FAIL	sigs.k8s.io/security-profiles-operator/test	150.436s
FAIL
make: *** [test-e2e] Error 1
```
 </details>

#### Environment:

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): darwin
- Kernel (e.g. `uname -a`):
- Others:

**Comment by naveensrinivasan** [comment]
https://github.com/kubernetes-sigs/security-profiles-operator/pull/185

**Comment by naveensrinivasan** [comment]
The #185 fixed this and now e2e works on osx.

**Comment by saschagrunert** [comment]
Thank you @naveensrinivasan ! :pray:
